import Head from "next/head";

import Featured from "../components/Featured";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Astrologie Sanatan</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="Keywords"
          content="  výklad horoskopu, astrologické konzultace, váš védský horoskop "
        />
        <link rel="icon" href="/img/logosvg.svg" />
      </Head>
      <Featured />
    </div>
  );
}
